name: CI by Bot

on:
  push:
    branches: 
      - master

jobs:

  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # https://docs.docker.com/engine/reference/commandline/build/
    - name: Build in virtual environment
      run: |        
        docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/arde:latest .

    # https://docs.docker.com/engine/reference/commandline/save/
    - name: Save in virtual environment
      run: |
        docker save docker.pkg.github.com/francisfuzz/actions-registry-docker-example/arde:latest | gzip > myimage_latest.tar.gz

    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts
    - name: Upload image as artifact
      uses: actions/upload-artifact@v1
      with:
        name: image
        path: myimage_latest.tar.gz

  download_and_publish:
    needs: build_and_upload
    runs-on: ubuntu-latest

    steps:
    - name: Download image from artifact
      uses: actions/download-artifact@v1
      with:
        name: image

    # https://docs.docker.com/engine/reference/commandline/import/
    - name: Import image locally
      run: |
        ls -Ralth 
        cat image/myimage_latest.tar.gz | docker import - docker.pkg.github.com/francisfuzz/actions-registry-docker-example/arde:latest

    # https://docs.docker.com/engine/reference/commandline/images/
    - name: List images
      run: |
        docker images 

    # https://help.github.com/en/github/managing-packages-with-github-packages/configuring-docker-for-use-with-github-packages#authenticating-with-the-github_token
    - name: Login to GPR for Docker
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        docker login docker.pkg.github.com -u francisfuzz -p $GITHUB_TOKEN

    # https://help.github.com/en/github/managing-packages-with-github-packages/configuring-docker-for-use-with-github-packages#publishing-a-package
    - name: Publish to GPR
      run: |        
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/arde:latest
